config/routes.rb
Rails.application.routes.draw do
devise_for :users
# devise_scope :user do
#   get 'login', to: 'users/sessions#new'
#   get 'signup', to: 'users/registrations#new'

# end

  resources :users, only: [:show, :edit, :update]
  root to: "activities#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :activities do
    resources :bookings, only: [:create, :update]
  end

  get "/myactivities", to: "activities#myactivities", as: "myactivities"

  get "/myactivities/:id", to: "activities#show_myactivities", as: "show_myactivities"

  get "/mybookings", to: "bookings#mybookings", as: "mybookings"
  resources :bookings, only: [:show]
  get '/myprofile', to: 'users#myprofile'


end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :activity
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  has_many :activities
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy show_myactivities ]

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(params_activity)
    @activity.user_id = current_user.id
    if @activity.save
      redirect_to activity_path(@activity)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @search = params[:query] if params[:query]
    @activities = Activity.where("(description ILIKE ? OR title ILIKE ?) ", "%#{@search}%", "%#{@search}%").and(Activity.where.not(user_id: current_user))
    if params[:at]
      @at = params[:at]
      @km = params[:km] if params[:km]
      @activities = @activities.near(@at, @km) unless params[:at].empty?
    end

    @markers = @activities.geocoded.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {activity: activity})
      }
    end
  end

  def show
    @booking = Booking.new
    @markers = [{
      lat: @activity.latitude,
      lng: @activity.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: {activity: @activity})
    }] if @activity.geocoded?
  end

  def edit
    unless current_user == @activity.user
      redirect_to user_path(current_user), notice: "You can't modify other's activities."
    end
  end

  def update
    if @activity.update(params_activity)
      redirect_to activity_path(@activity), notice: "Activity was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    redirect_to user_path(current_user), notice: "You can't destroy other's activities."
    @activity.destroy
    redirect_to activities_path, notice: "Activity was successfully destroyed."
  end

  def myactivities
    @activities = Activity.where(user_id: current_user)
    @bookings_to_validate = []
    @activities.each do |activity|
      @bookings_to_validate << activity.bookings.select { |booking| booking.validation.nil? }
    end
    @bookings_to_validate.flatten
    @bookings_incoming = []
    @activities.each do |activity|
      @bookings_incoming << activity.bookings.select { |booking| booking.validation == true && booking.date >= Date.today() }
    end
    @bookings_incoming.flatten
  end

  def show_myactivities
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def params_activity
    params.require(:activity).permit(:title, :description, :location, :poster_url, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :description])
  end



end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_activity, only: %i[ new, create  ]
  require 'date'

  def create
    @booking = Booking.new(params_booking)
    @booking.user_id = current_user.id
    @booking.activity_id = @activity.id
    if @booking.save
      redirect_to mybookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def mybookings
    @bookings = Booking.where(user_id: current_user).sort_by{|book| book.date}.group_by {|booking| Date::MONTHNAMES[booking.date.month].upcase.first(3)}
  end

  def update
    @response = params[:response]
    @activity = Activity.find(params[:activity_id])
    Booking.find(params[:id]).update(validation: @response)
    redirect_to myactivities_path, notice: "Booking was successfully validated."
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def set_activity
    @activity = Activity.find(params[:activity_id])
  end

  def params_booking
    params.require(:booking).permit(:date)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def show
    @messages = Message.where(booking: @booking)
  end

  def create
    @message = Message.new(content: params["message"]["content"])
    @message.booking = Booking.find(params[:booking_id])
    @message.sender = current_user.id
    @message.save
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home

  def home
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def create

  end

  def edit

  end

  def update
  end

  def myprofile
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_activity.html.erb
<% path = activity.photo.attached? ? cl_image_path(activity.photo.key) : asset_path( 'logo_friend.png')%>
<%= link_to activity_path(activity) do %>

<div class="card-trip a-none">

  <img src="<%= path %>" style="width: 100%; height: 200px; object-fit: cover;" class="zoom">

    <div class="card-trip-infos">
      <div>
       <h2><%= activity.title %></h2>
       <h2 class="user-name"><span>with </span> <%= activity.user.name %></h2>
        <p><i class="fa-sharp fa-solid fa-location-dot me-1"></i><!--Location:--><%= activity.location %></p>
        <!--<p><strong>Description:</strong><%= activity.description %> <strong>Owner:</strong>
        <%= activity.user.name %></p>-->
      </div>

          <%= link_to user_path(activity.user) do%>

            <img src="<%= cl_image_path(activity.user.photo.key) %>" class="card-trip-user avatar-bordered" style="object-fit: cover;"/>
          <%end%>
  </div>
</div>
<% end %>

app/views/activities/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class ="col-6">
      <%= simple_form_for @activity do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :location %>
        <%#= f.input :poster_url %>
        <%= f.input :photo, as: :file %>
        <div class="d-flex justify-content-center"><%= f.button :submit, class: 'btn btn-primary'%></div>
      <% end %>
    </div>
  </div>
</div>

app/views/activities/_info_window.html.erb
<h2><%= activity.title %></h2>
<p><%= activity.description %></p>

app/views/activities/_list.html.erb
<% activities.each do |activity| %>
    <div class=" col-md-4 col-xxl-2 .col-sm-12 mt-5 a-none">
      <%= link_to activity_path(activity) do %>
        <%= render activity, user: activity.user %>
      <% end %>
    </div>
<% end %>

app/views/activities/_map.html.erb
<div style="width: 100%; height: 600px;">
</div>

app/views/activities/_search_form.html.erb
<%= simple_form_for @activities do |f| %>
  <%= f.input :query %>
  <%= f.input :location, data: { controller: "search-bar", search_bar_target: "location", search_bar_api_key_value: ENV["MAPBOX_API_KEY"]} %>
  <%= f.select :km, [5, 10, 20]%>
  <%= f.label :km, "km" %>
  <%= f.submit "Search" %>
<% end %>

app/views/activities/_show_activity.html.erb
<% path = activity.photo.attached? ? cl_image_path(activity.photo.key) : asset_path( 'logo_friend.png')%>
<%= link_to activity_path(activity) do %>

<div class="card-trip a-none">

  <img src="<%= path %>" style="width: 100%; height:400px; object-fit: cover;" class="zoom">

    <div class="card-trip-infos">
      <div>
       <h2><%= activity.title %></h2>
       <h2 class="user-name"><span>with </span> <%= activity.user.name %></h2>
        <p><i class="fa-sharp fa-solid fa-location-dot me-1"></i><!--Location:--><%= activity.location %></p>
        <!--<p><strong>Description:</strong><%= activity.description %> <strong>Owner:</strong>
        <%= activity.user.name %></p>-->
      </div>

          <%= link_to user_path(activity.user) do%>

            <img src="<%= cl_image_path(activity.user.photo.key) %>" class="card-trip-user avatar-bordered" style="object-fit: cover;"/>
          <%end%>
  </div>
</div>
<% end %>

app/views/activities/_status.html.erb
<% if booking.validation.nil? %>
<div class=" pe-2">
  <%= link_to activity_booking_path(@activity, booking, :response => true), data: { turbo_method: :patch, turbo_confirm: "Are you sure ?" } do %>
    <i class="fa-solid fa-square-check display-6"></i>
  <% end %>
</div>
<div>
  <%= link_to activity_booking_path(@activity, booking, :response => false), data: { turbo_method: :patch, turbo_confirm: "Are you sure ?" } do %>
    <i class="fa-solid fa-square-xmark display-6"></i>
  <% end %>
</div>
<% elsif booking.validation == true %>
  <p>ACCEPTED</p>
<% elsif booking.validation == false %>
  <p>DECLINED</p>
<% end %>

app/views/activities/edit.html.erb
<%= render "form" %>

app/views/activities/index.html.erb
<div class="row">

  <!-- activities grid -->
  <div class="col-8" id="activities" data-controller="map" data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    <div class="d-flex mb-5" style="justify-content: space-between;">
      <h1>Activities</h1>
    </div>
    <div class="row">
      <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Activity</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false" data-action="click->map#loadmap">Map</button>
        </li>
      </ul>
    </div><!-- row end -->

    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
        <div class="row">
          <!--------------------------------------- T A B 1 - C O N T E N T------------------------------------------------------------------------------------->
            <% @activities.each do |activity| %>
              <div class="col-md-4 col-xxl-4 col-sm-12 mt-5 a-none">
                <%= render "activity", activity: activity %>
              </div>
            <% end %>
          <!--------------------------------------- T A B 1 — E N D ------------------------------------------------------------------------------------->
        </div> <!-- row end -->
      </div> <!-- tab-pane 1 end -->
      <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="1">
        <!--------------------------------------- T A B 2  - C O N T E N T------------------------------------------------------------------------------------->
        <div class="" id="map" data-map-target="map">
          <%= render "activities/map" %>
        </div>
        <!--------------------------------------- T A B 2 — E N D ------------------------------------------------------------------------------------->
      </div> <!-- end pane 2 -->
    </div> <!-- end tab content -->
  </div><!-- end col 8 -->


  <div class="col-4" style="">
    <div style="background-color: #FFF; border-radius: 10px; padding:2rem; position: sticky; top: 18rem;">
      <div class="mb-3">
        <%= form_with url: activities_path, method: :get do |f|  %>
          <div class="form-floating mb-3">
            <%= f.text_field :query, class: "form-control mb-3", id: "floatingInput", placeholder: "name@example.com" %>
            <%= f.label "Search for:", for:"floatingInput" %>
          </div><!-- end form -->

          <div data-controller="search-bar" class="form-group">
            <%= f.text_field :at, data: { action: "keyup->search-bar#autocomplete", 'search-bar-target': "input" },
            class:"form-control mb-3", list:"datalistOptions", label:"" %>
            <datalist id="datalistOptions" data-search-bar-target="results">

            <%= f.label :at, "at:", for:"floatingSelect" %>
            </datalist>
          </div><!-- end data controller -->

          <div class="d-flex justify-content-between">
            <div>
              <%= f.select :km, [5, 10, 20], class:"form-select", id:"floatingSelect", ariaLabel:"Floating label select example" %>
              <%= f.label :km, "km", for:"floatingSelect" %>
            </div>
            <div>
              <%= f.submit "Search", class: "btn btn-flat"%>
            </div>
          </div><!-- end d-flex -->

        <% end %>
      </div><!-- end mb3 -->
    </div>
  </div><!-- end col 4 -->
</div><!-- end primary row -->

app/views/activities/myactivities.html.erb
<div class="row">
  <div class="col-8">
    <div class="row">
      <div class="d-flex justify-content-between">
        <h1>My activities</h1>
        <div>
        <%= link_to "+ New activity", new_activity_path, class: "btn btn-flat" %>
        </div>
      </div>
      <% @activities.each do |activity| %>
        <div class=" col-md-4 col-xxl-4 col-sm-12 mt-5 a-none">
          <%= link_to show_myactivities_path(activity) do %>
            <%= render activity %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-4">
    <div class="p-3 bg-white rounded-4" style="position: sticky; top:5rem">
      <div class="row">
        <h2>Bookings to validate</h2>
          <% @bookings_to_validate.flatten.each do |booking_to_validate| %>
          <div class="d-flex justify-content-between align-items-center">
            <div class="d-flex align-items-center">
              <img src="<%= cl_image_path(booking_to_validate.user.photo.key, height: 900) %>" class="card-trip-user avatar-bordered"  style="width:40px; height:40px;"/>
              <div class="ps-2">
                <% @activity = booking_to_validate.activity %>
                <p class="my-0"><strong><%= @activity.title %></strong> with <%= booking_to_validate.user.name %></p>
                <p class="my-0"><%= booking_to_validate.date %> </p>
              </div>
            </div>
            <div class="d-flex">
              <%= render "status", booking: booking_to_validate %>  </p>
            </div>
          </div>
          <% end %>
      </div>
      <div class="row mt-3">
        <h2>Bookings incoming</h2>
        <% @bookings_incoming.flatten.sort_by{|book| book.date}.each do |booking_incoming| %>
          <% @activity = booking_incoming.activity %>
          <div class="d-flex align-items-center">
            <img src="<%= cl_image_path(booking_incoming.user.photo.key, height: 900) %>" class="card-trip-user avatar-bordered" style="width:40px; height:40px;"/>
            <div class="ps-2">
              <p class="my-0"><strong><%= @activity.title %></strong> with <%= booking_incoming.user.name %> </p>
              <p class="my-0"><%= booking_incoming.date %> </p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/activities/new.html.erb
<h1 class="text-center">Post a new activity</h1>
  <%# <div class="border border-secondary" class="shadow-sm p-3 mb-5 bg-white rounded"> %>
    <%= render "form" %>
    <div class="text-center mt-4">
      <%= link_to "Back to activities", activities_path%>
    </div>
  <%# </div> %>

app/views/activities/show.html.erb
<div class="container d-flex justify-content-around" data-controller="map" data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  <div class="flex-grow-1 pe-3" id="yolo">
    <%= render @activity || "show_activity" %><br/>

    <p><strong>Description :</strong></p><%= @activity.description %>
    <div class="" id="map" data-map-target="map">
      <%= render "activities/map" %>
    </div>
    <div class="mt-5 mb-5">
      <%= link_to "Back to activities", activities_path %>
    </div>
  </div>


  <div class="p-3 pt-5" style="border: #FFFFFF; border-radius: 50px; height: 300px; background-color: white;">
    <%= simple_form_for [@activity, @booking] do |f| %>
    <%= f.input :date%>
    <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/activities/show_myactivities.html.erb
<div class="container">
  <%= render @activity %>
  <% @activity.bookings.each do |booking| %>
    <p><%= booking.date %> by <%= booking.user.name %> <%= render "status", booking: booking %>  </p>
  <% end %>
  <%= link_to "Edit this activity", edit_activity_path(@activity) %>
  <%= link_to "Delete this activity", activity_path(@activity), data: { turbo_method: :delete, turbo_confirm: "Are you sure ?" } %>
  <%= link_to "Back to my activities", myactivities_path %>
</div>

app/views/bookings/_booking.html.erb
<% path = booking.activity.photo.attached? ? cl_image_path(booking.activity.photo.key, height: 300, crop: :fill) : asset_path("logo_friend.png")%>
<%= link_to booking_path(booking), class: "w-100" do %>
  <div class="card-product mb-3">
    <img src=<%= path %> />
    <div class="card-product-infos">
      <div class="d-flex justify-content-between">
        <div>
          <h2><%= booking.activity.title %></h2>
          <p><%= booking.activity.description %></p>
          <p><i class="fa-sharp fa-solid fa-location-dot me-1"></i><%= booking.activity.location %><p>
        </div>
        <div>
          <h2 class="pb-2"><%= booking.date %></h2>
          <%= render "status", booking: booking %>
          <p><strong>By: </strong><%= booking.activity.user.name %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/bookings/_status.html.erb
<% if booking.validation.nil? %>
  <p style="font-size: 14px;"><i class="fa-solid fa-clock"></i> PENDING</p>
<% elsif booking.validation == true %>
  <p style="font-size: 14px;"><i class="fa-solid fa-square-check"></i> ACCEPTED</p>
<% elsif booking.validation == false %>
  <p style="font-size: 14px;"><i class="fa-solid fa-square-xmark"></i> DECLINED</p>
<% end %>

app/views/bookings/mybookings.html.erb
<h1>My bookings</h1>
<% @bookings.each do |month_bookings| %>
  <div class="a-none">
    <% month_bookings[1].sort_by{|book| book.date}.each_with_index do |booking, index| %>
      <% if index == 0 %>
        <div class="border-top my-3"></div>
      <% end %>
      <div class="d-flex">
        <div style="width: 5rem; color:rgba(0, 0, 0, 0.55);"><%= index == 0 ? month_bookings[0] : " " %></div>
        <%= render "booking", booking: booking %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/bookings/show.html.erb
<%= @booking.date %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Rentafriend</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('logo_friend.png') %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render "shared/navbar" %>
  <div class="container" style="margin-top:5rem; min-height:82vh;">

    <%= yield %>


    </div>
        <div class="footer" style="backdrop-filter: blur(8px); background-color: rgba(244, 244, 244, 0.3); ">
        <div class="footer-links">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>

        <div class="footer-copyright">
          This footer is made by Agnes, Théo & Flo with <i class="fas fa-heart"></i> at Le Wagon
        </div>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<p style="text-align: left;"> <%= User.find(message.sender).name %> : <%= message.content %> </p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="d-flex">
      <%= link_to activities_path, class: "navbar-brand" do %>
        <%= image_tag 'logo_friend.png' %>
      <% end %>
      <h5 class="mt-3" style="color: rgb(130, 61, 135)">Rent a Friend</h5>
    </div>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", activities_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My bookings", mybookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My activities list", myactivities_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% path = current_user.photo.attached? ? cl_image_path(current_user.photo.key, height: 600, crop: :fill) : asset_path( 'default_profil.png')%>
              <%= image_tag src=path , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", myprofile_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/myprofile.html.erb
<h1>My profile</h1>
<div class="container d-flex mt-4">
  <div>
    <% path = current_user.photo.attached? ? cl_image_path(current_user.photo.key, height: 300, crop: :fill) : asset_path( 'default_profil.png')%>
    <img src="<%=path%>" height="260" width="260" class="rounded-circle">
  </div>

  <div class= "mt-3 ms-5">
    <p><strong>Name:</strong> <%= current_user.name %></p>
    <p><strong>E-mail:</strong> <%= current_user.email %></p>
    <p><strong>Description:</strong> <%= current_user.description %></p>
  </div>
</div>


<div class="mt-4 ms-5 ps-4">
  <%= link_to "Edit my information", edit_user_registration_path %>
</div>

app/views/users/show.html.erb
<div class="text-center">
  <h1>Profile details</h1>
</div>

<div class="container d-flex flex-column justify-content-center pt-3" style="border: 1px solid #DCDCDC; width:30%; border-radius: 20px; background-color:#DCDCDC; ">
  <div class="ps-4">
    <img src="<%= cl_image_path(@user.photo.key) %>" height="260" width="260" class="rounded-circle" style="object-fit: cover;">
  </div>

  <div>
    <p><strong>Name:</strong> <%= @user.name %></p>
    <p><strong>E-mail:</strong> <%= @user.email %></p>
    <p><strong>Description:</strong> <%= @user.description %></p>
  </div>
</div>